:linkattrs:
:experimental:

= Istio Add-on

This add-on deploys the https://Istio.io/[Istio] **servicemesh** on to Minishift-provisioned OpenShift cluster.  The Istio is provisioned using https://github.com/Maistra/openshift-ansible/blob/maistra-0.2.0/istio/Installation.md[Istio Operator].

[NOTE]
====
- The add-on was tested with Maistra (v0.2.0)
- The add-on uses Istio Operator v0.2.0
- This add-on depends on admin-user and anyuid  Minishift addons
====

== Minishift profile setup

As this Istio setup deploys applications like *istio-galley*,*istio-ingress*, *istio-egress*, *istio-pilot*,*elasticsearch*,*jaeger**,*kiali*, *grafana*, *prometheus* with their related resources
such as https://kubernetes.io/docs/tasks/configure-pod-container/configmap/[configmaps], https://kubernetes.io/docs/concepts/configuration/secret/[secrets]
and https://kubernetes.io/docs/concepts/api-extension/custom-resources/[Custom Resource Definitions], it is ideal to setup a Minishift profile with the following configuration:

[sources,bash]
----
$ minishift profile set servicemesh <1>
$ minishift config set memory 8GB <2>
$ minishift config set cpus 4 <3>
$ minishift config set image-caching true <4>
$ minishift config set openshift-version v3.10.0 <5>
$ minishift addon enable admin-user <6>
$ minishift addon enable anyuid <7>
$ minishift start <8>
----

<1> Create a new Minishift profile named **servicemesh**
<2> Use 8GB of memory for Istio and apps that you might deploy later
<3> 4 CPUs results in a maximum of 30 pods, since Istio deploys approximately 9 pods at minimum
<4> Caches the downloaded container images for future use
<5> Pinning OpenShift version to v3.10.0, so that upgrade of minishift does not recreate the OpenShift cluster
<6> Creates a new user called **admin** with **cluster-admin** role
<7> Allows containers within OpenShift to be run with any user id 
<8> Since we have set the profile to be **servicemesh**, this command starts Minishift with profile **servicemesh**

== Install add-on

Run the following command to install `istio` add-on:

[source,bash]
----
$ git clone https://github.com/minishift/minishift-addons
$ minishift addon install ./minishift-addons/add-ons/istio
----

== Deploy Istio

Run the following command to apply `istio` add-on:

[source,bash]
----
$ minishift addon enable istio <1>
$ minishift addon apply istio <2>
----
<1> Enabling the **istio** addon allows the addon to be automatically applied during profile recreation i.e. minishift delete && minishift start 
<2> The command will take few minutes, you can watch the status with command `oc -n istio-system get pods -w --as system:admin`, you can terminate watch with kbd:[CTRL + C]

== Undeploy Istio

Removing the `istio` add-on will undeploy Istio from the Minishift-provisioned OpenShift cluster.

Run the following command to remove the `istio` add-on:

[source,bash]
----
$ minishift addon remove istio
----

== Uninstall Istio add-on

Run the following command to delete and remove the `istio` add-on artifacts from the machine:

[soource,bash]
----
$ minishift addon uninstall istio
----
