:linkattrs:

= Istio Add-on

This add-on deploys the https://Istio.io/[Istio] **servicemesh** on to Minishift-provisioned OpenShift cluster.

NOTE: The add-on was tested with Istio release v1.0.2

== Minishift profile setup

The standard Istio setup deploys around four to five applications like *istio-ingress*, *istio-egress*, *istio-pilot*, *grafana*, *prometheus* and their related resources
such as https://kubernetes.io/docs/tasks/configure-pod-container/configmap/[configmaps], https://kubernetes.io/docs/concepts/configuration/secret/[secrets]
and https://kubernetes.io/docs/concepts/api-extension/custom-resources/[Custom Resource Definitions].

Considering this, it is ideal to setup a Minishift profile with the following configuration:

[code,sh]
----
$ minishift profile set servicemesh <1>
$ minishift config set memory 8GB <2>
$ minishift config set cpus 3 <3>
$ minishift addon enable dynamic-admission-controllers #optional <4>
$ minishift addon enable istio
$ minishift start servicemesh<5>
----

<1> Create a new Minishift profile named **servicemesh**
<2> Use 8GB of memory for Istio and apps that you might deploy later
<3> 3 CPUs results in a maximum of 30 pods, since Istio deploys approximately 9 pods at minimum
<4> Enable the Minishift `dynamic-admission-controllers` add-on if you want to use auto injection of side-car container.
<5> Since we have set the profile to be **servicemesh**, this command starts Minishift with profile **servicemesh**

== Preparing Istio
Download Istio corresponding to your platform from https://github.com/istio/istio/releases[Download an Istio release] extract it to a folder of your choice
and export that folder as `ISTIO_HOME`.

On macOS/Linux machines you can use the following commands to download the latest version of Istio and set the `ISTIO_HOME` environment variable:

== Install add-on

Run the following command to install `istio` add-on:

[code,sh]
----
$ git clone https://github.com/minishift/minishift-addons
$ minishift addon install ./minishift-addons/add-ons/dynamic-admissoin-controllers #optional
$ minishift addon install ./minishift-addons/add-ons/istio
----

== Deploy Istio

Run the following command to apply `istio` add-on:

[code,sh]
----
$ minishift addon apply dynamic-admission-controllers #optional
$ minishift addon apply istio
----

== Undeploy Istio

Removing the `istio` add-on will undeploy Istio from the Minishift-provisioned OpenShift cluster.

Run the following command to remove the `istio` add-on:

[code,sh]
----
$ minishift addon remove istio
----

== Uninstall Istio add-on

Run the following command to delete and remove the `istio` add-on artifacts from the machine:

[code,sh]
----
$ minishift addon uninstall istio
----
