apiVersion: v1
kind: ClusterRole
metadata:
  name: management-infra-admin
rules:
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - "get"
- apiGroups:
  - ""
  resources:
  - pods/proxy
  verbs:
  - "*"

