apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: che-template
message: Eclipse Che in Minishift template
metadata:
  annotations:
    description: Eclipse Che in Minishift
    openshift.io/display-name: eclipse-che
    template.openshift.io/provider-display-name: 'Red Hat, Inc.'
    template.openshift.io/support-url: 'https://access.redhat.com'
  name: che-single-user
parameters:
  - description: The domain name without the project name
    displayName: Che service domain name
    name: DOMAIN_NAME
    require: true
    value: ""
  - displayName: Che Image Tag
    description: The docker image tag to be used for che, available are latest (5.19.0-centos), nightly(5.20.0-SNAPSHOT)
    name: IMAGE_TAG
    value: latest
    required: false
  - displayName: ImageStream Namespace
    description: Namespace in which the ImageStreams for Che Server images are installed. These ImageStreams are normally installed in the openshift namespace. You should only need to modify this if you've installed the ImageStreams in a different namespace/project.
    name: IMAGE_STREAM_NAMESPACE
    value: openshift
    required: true
objects:
  - apiVersion: v1
    kind: RoleBinding
    metadata:
      name: che
    roleRef:
      name: admin
    subjects:
    - kind: ServiceAccount
      name: che
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      labels:
        app: che
        provider: fabric8
        version: 2.0.35
        group: io.fabric8.tenant.apps
      name: che
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        fabric8.io/app-menu: development
        fabric8.io/git-commit: aae4af49facadd2626d89d2064eeff74d3aad8c2
        fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/tenant-che.git/tenant-che-apps/che
        fabric8.io/scm-url: http://github.com/fabric8io/tenant-che/tenant-che-apps/che
        fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/tenant-che/tenant-che-apps/che/master/apps/che/src/main/fabric8/icon.png
        fabric8.io/git-branch: release-v2.0.35
        fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/tenant-che.git/tenant-che-apps/che
        fabric8.io/scm-tag: fabric8io/tenant-che-1.0.0
      labels:
        app: che
        provider: fabric8
        expose: "false"
        version: 2.0.35
        group: io.fabric8.tenant.apps
      name: che-host
    spec:
      ports:
      - name: http
        port: 8080
        protocol: TCP
        targetPort: 8080
      selector:
        app: che
        provider: fabric8
        group: io.fabric8.tenant.apps
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        app: che
        provider: fabric8
        version: 2.0.35
        group: io.fabric8.tenant.apps
      name: che-data-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        app: che
        provider: fabric8
        version: 2.0.35
        group: io.fabric8.tenant.apps
      name: claim-che-workspace
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      labels:
        app: che
        provider: fabric8
        version: 2.0.35
        group: io.fabric8.tenant.apps
      name: che
    data:
      hostname-http: ${CHE_OPENSHIFT_PROJECT}.${DOMAIN_NAME}
      workspace-storage: /home/user/che/workspaces
      workspace-storage-create-folders: "false"
      local-conf-dir: /etc/conf
      openshift-serviceaccountname: che
      che-server-evaluation-strategy: docker-local-custom
      che.logs.dir: /data/logs
      che.docker.server_evaluation_strategy.custom.template: <serverName>-<if(isDevMachine)><workspaceIdWithoutPrefix><else><machineName><endif>-<externalAddress>
      che.docker.server_evaluation_strategy.custom.external.protocol: http
      che.predefined.stacks.reload_on_start: "false"
      log-level: INFO
      docker-connector: openshift
      port: "8080"
      remote-debugging-enabled: "true"
      che-oauth-github-forceactivation: "true"
      workspaces-memory-limit: 1900Mi
      workspaces-memory-request: 1100Mi
      enable-workspaces-autostart: "false"
      keycloak-oso-endpoint: https://sso.openshift.io/auth/realms/fabric8/broker/openshift-v3/token
      keycloak-github-endpoint: https://sso.openshift.io/auth/realms/fabric8/broker/github/token
      keycloak-disabled: "true"
      che-server-java-opts: -XX:+UseG1GC -XX:+UseStringDeduplication -XX:MinHeapFreeRatio=20
        -XX:MaxHeapFreeRatio=40 -XX:MaxRAM=600m -Xms256m
      che-workspaces-java-opts: -XX:+UseG1GC -XX:+UseStringDeduplication -XX:MinHeapFreeRatio=20
        -XX:MaxHeapFreeRatio=40 -XX:MaxRAM=1200m -Xms256m
      che-openshift-secure-routes: "false"
      che-secure-external-urls: "false"
      che-server-timeout-ms: "3600000"
      che-openshift-precreate-subpaths: "true"
      che-workspace-auto-snapshot: "false"
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      annotations:
        fabric8.io/git-commit: aae4af49facadd2626d89d2064eeff74d3aad8c2
        fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=che&var-version=2.0.35
        fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/tenant-che.git/tenant-che-apps/che
        fabric8.io/scm-url: http://github.com/fabric8io/tenant-che/tenant-che-apps/che
        fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/tenant-che/tenant-che-apps/che/master/apps/che/src/main/fabric8/icon.png
        fabric8.io/git-branch: release-v2.0.35
        fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/tenant-che.git/tenant-che-apps/che
        fabric8.io/scm-tag: fabric8io/tenant-che-1.0.0
      labels:
        app: che
        provider: fabric8
        version: 2.0.35
        group: io.fabric8.tenant.apps
      name: che
    spec:
      replicas: 1
      revisionHistoryLimit: 2
      selector:
        app: che
        provider: fabric8
        group: io.fabric8.tenant.apps
      strategy:
        recreateParams:
          timeoutSeconds: 10000
        type: Recreate
      template:
        metadata:
          annotations:
            fabric8.io/git-commit: aae4af49facadd2626d89d2064eeff74d3aad8c2
            fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=che&var-version=2.0.35
            fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/tenant-che.git/tenant-che-apps/che
            fabric8.io/scm-url: http://github.com/fabric8io/tenant-che/tenant-che-apps/che
            fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/tenant-che/tenant-che-apps/che/master/apps/che/src/main/fabric8/icon.png
            fabric8.io/git-branch: release-v2.0.35
            fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/tenant-che.git/tenant-che-apps/che
            fabric8.io/scm-tag: fabric8io/tenant-che-1.0.0
          labels:
            app: che
            provider: fabric8
            version: 2.0.35
            group: io.fabric8.tenant.apps
        spec:
          containers:
          - env:
            - name: CHE_DOCKER_IP_EXTERNAL
              valueFrom:
                configMapKeyRef:
                  key: hostname-http
                  name: che
            - name: CHE_WORKSPACE_STORAGE
              valueFrom:
                configMapKeyRef:
                  key: workspace-storage
                  name: che
            - name: CHE_LOGS_DIR
              valueFrom:
                configMapKeyRef:
                  key: che.logs.dir
                  name: che
            - name: CHE_WORKSPACE_STORAGE_CREATE_FOLDERS
              valueFrom:
                configMapKeyRef:
                  key: workspace-storage-create-folders
                  name: che
            - name: CHE_LOCAL_CONF_DIR
              valueFrom:
                configMapKeyRef:
                  key: local-conf-dir
                  name: che
            - name: CHE_OPENSHIFT_PROJECT
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CHE_OPENSHIFT_SERVICEACCOUNTNAME
              valueFrom:
                configMapKeyRef:
                  key: openshift-serviceaccountname
                  name: che
            - name: CHE_DOCKER_SERVER__EVALUATION__STRATEGY
              valueFrom:
                configMapKeyRef:
                  key: che-server-evaluation-strategy
                  name: che
            - name: CHE_DOCKER_SERVER__EVALUATION__STRATEGY_CUSTOM_TEMPLATE
              valueFrom:
                configMapKeyRef:
                  key: che.docker.server_evaluation_strategy.custom.template
                  name: che
            - name: CHE_DOCKER_SERVER__EVALUATION__STRATEGY_CUSTOM_EXTERNAL_PROTOCOL
              valueFrom:
                configMapKeyRef:
                  key: che.docker.server_evaluation_strategy.custom.external.protocol
                  name: che
            - name: CHE_PREDEFINED_STACKS_RELOAD__ON__START
              valueFrom:
                configMapKeyRef:
                  key: che.predefined.stacks.reload_on_start
                  name: che
            - name: CHE_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: log-level
                  name: che
            - name: CHE_PORT
              valueFrom:
                configMapKeyRef:
                  key: port
                  name: che
            - name: CHE_DOCKER_CONNECTOR
              valueFrom:
                configMapKeyRef:
                  key: docker-connector
                  name: che
            - name: CHE_DEBUG_SERVER
              valueFrom:
                configMapKeyRef:
                  key: remote-debugging-enabled
                  name: che
            - name: CHE_OAUTH_GITHUB_FORCEACTIVATION
              valueFrom:
                configMapKeyRef:
                  key: che-oauth-github-forceactivation
                  name: che
            - name: CHE_OPENSHIFT_WORKSPACE_MEMORY_OVERRIDE
              valueFrom:
                configMapKeyRef:
                  key: workspaces-memory-limit
                  name: che
            - name: CHE_OPENSHIFT_WORKSPACE_MEMORY_REQUEST
              valueFrom:
                configMapKeyRef:
                  key: workspaces-memory-request
                  name: che
            - name: CHE_WORKSPACE_AUTO__START
              valueFrom:
                configMapKeyRef:
                  key: enable-workspaces-autostart
                  name: che
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  key: che-server-java-opts
                  name: che
            - name: CHE_WORKSPACE_JAVA_OPTIONS
              valueFrom:
                configMapKeyRef:
                  key: che-workspaces-java-opts
                  name: che
            - name: CHE_OPENSHIFT_SECURE_ROUTES
              valueFrom:
                configMapKeyRef:
                  key: che-openshift-secure-routes
                  name: che
            - name: CHE_DOCKER_SERVER__EVALUATION__STRATEGY_SECURE_EXTERNAL_URLS
              valueFrom:
                configMapKeyRef:
                  key: che-secure-external-urls
                  name: che
            - name: CHE_OPENSHIFT_SERVER_INACTIVE_STOP_TIMEOUT_MS
              valueFrom:
                configMapKeyRef:
                  key: che-server-timeout-ms
                  name: che
            - name: CHE_OPENSHIFT_PRECREATE_WORKSPACE_DIRS
              valueFrom:
                configMapKeyRef:
                  key: che-openshift-precreate-subpaths
                  name: che
            - name: CHE_KEYCLOAK_OSO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: keycloak-oso-endpoint
                  name: che
            - name: CHE_KEYCLOAK_GITHUB_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: keycloak-github-endpoint
                  name: che
            - name: CHE_KEYCLOAK_DISABLED
              valueFrom:
                configMapKeyRef:
                  key: keycloak-disabled
                  name: che
            - name: CHE_WORKSPACE_AUTO__SNAPSHOT
              valueFrom:
                configMapKeyRef:
                  key: che-workspace-auto-snapshot
                  name: che
            image: "che-server"
            imagePullPolicy: "IfNotPresent"
            livenessProbe:
              httpGet:
                path: /api/system/state
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 120
              timeoutSeconds: 10
            name: che
            ports:
            - containerPort: 8080
              name: http
            - containerPort: 8000
              name: http-debug
            readinessProbe:
              httpGet:
                path: /api/system/state
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 15
              timeoutSeconds: 60
            resources:
              limits:
                memory: 600Mi
              requests:
                memory: 256Mi
            volumeMounts:
            - mountPath: /data
              name: che-data-volume
          serviceAccountName: che
          volumes:
          - name: che-data-volume
            persistentVolumeClaim:
              claimName: che-data-volume
      triggers:
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
          - che
          from:
            kind: ImageStreamTag
            namespace: "${IMAGE_STREAM_NAMESPACE}"
            name: che-server:${IMAGE_TAG}
      - type: ConfigChange
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: che
        provider: fabric8
        version: 2.0.35
        group: io.fabric8.tenant.apps
      name: che
    spec:
      to:
        kind: Service
        name: che-host


